# Introduction to Plotly Express


**Plotly Express** is the high-level interface to Plotly, designed for quick and easy data visualization. It allows you to create interactive, customizable plots with minimal code.

**Key topics**

1. What is Plotly Express?
2. Working with the Gapminder Dataset
3. Core Plotly Express Plot Types
   - Scatter Plots
   - Line Plots
   - Bar Charts
   - Bubble Charts
   - Faceted Plots
4. Customizing Plots
5. Interactivity in Plotly Express


**Read through the documentation here:** https://plotly.com/python/plotly-express/

____

# 1. What is Plotly Express?

**Plotly Express** simplifies the creation of interactive visualizations. It’s:
- **Easy to use**: Generate complex plots with a few lines of code.
- **Interactive by default**: Zoom, pan, and hover without extra effort.
- **Pandas-integrated**: It works directly with Pandas DataFrames, making it great for handling tabular data.

___

# 2. Working with the Gapminder Dataset

The Gapminder dataset contains country-level data on life expectancy, population, and GDP per capita over time. This dataset is a great example to explore various types of plots.

In [108]:
import pandas as pd
import plotly.express as px

# load the built-in Gapminder dataset

gapminder_df = px.data.gapminder()

In [109]:
gapminder_df.head(25)

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
5,Afghanistan,Asia,1977,38.438,14880372,786.113360,AFG,4
6,Afghanistan,Asia,1982,39.854,12881816,978.011439,AFG,4
7,Afghanistan,Asia,1987,40.822,13867957,852.395945,AFG,4
8,Afghanistan,Asia,1992,41.674,16317921,649.341395,AFG,4
9,Afghanistan,Asia,1997,41.763,22227415,635.341351,AFG,4
10,Afghanistan,Asia,2002,42.129,25268405,726.734055,AFG,4
11,Afghanistan,Asia,2007,43.828,31889923,974.580338,AFG,4
12,Albania,Europe,1952,55.230,1282697,1601.056136,ALB,8
13,Albania,Europe,1957,59.280,1476505,1942.284244,ALB,8
14,Albania,Europe,1962,64.820,1728137,2312.888958,ALB,8
15,Albania,Europe,1967,66.220,1984060,2760.196931,ALB,8
16,Albania,Europe,1972,67.690,2263554,3313.422188,ALB,8
17,Albania,Europe,1977,68.930,2509048,3533.003910,ALB,8
18,Albania,Europe,1982,70.420,2780097,3630.880722,ALB,8
19,Albania,Europe,1987,72.000,3075321,3738.932735,ALB,8
20,Albania,Europe,1992,71.581,3326498,2497.437901,ALB,8
21,Albania,Europe,1997,72.950,3428038,3193.054604,ALB,8
22,Albania,Europe,2002,75.651,3508512,4604.211737,ALB,8
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
24,Algeria,Africa,1952,43.077,9279525,2449.008185,DZA,12

In [110]:
gapminder_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   object
 1   continent  1704 non-null   object
 2   year       1704 non-null   int64
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64
 5   gdpPercap  1704 non-null   float64
 6   iso_alpha  1704 non-null   object
 7   iso_num    1704 non-null   int64
dtypes: float64(2), int64(3), object(3)
memory usage: 106.6+ KB

In [111]:
gapminder_df['country'].nunique()

142

In [112]:
gapminder_df['country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium',
       'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Czech Republic',
       'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia',
       'Finland', 'France', 'Gabon', 'Gambia', 'Germany', 'Ghana',
       'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Haiti',
       'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Korea, Dem. Rep.',
       'Korea, Rep.', 'Kuwait', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Madagascar', 'Malawi', 'Malaysia', 'Mali', 'Mauritania',
       'Mauritius', 'Mexico', 'Mongolia', 'Montenegro', 'Morocco',
       'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Norway', 'Oman',
       'Pakistan', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Puerto Rico', 'Reunion', 'Romania', 'Rwanda',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia',
       'Somalia', 'South Africa', 'Spain', 'Sri Lanka', 'Sudan',
       'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tanzania', 'Thailand', 'Togo', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Uganda', 'United Kingdom', 'United States', 'Uruguay',
       'Venezuela', 'Vietnam', 'West Bank and Gaza', 'Yemen, Rep.',
       'Zambia', 'Zimbabwe'], dtype=object)

In [113]:
gapminder_df['year'].unique()

array([1952, 1957, 1962, 1967, 1972, 1977, 1982, 1987, 1992, 1997, 2002,
       2007])

In [114]:
gapminder_df['country'].value_counts()

country
Afghanistan           12
Albania               12
Algeria               12
Angola                12
Argentina             12
                      ..
Vietnam               12
West Bank and Gaza    12
Yemen, Rep.           12
Zambia                12
Zimbabwe              12
Name: count, Length: 142, dtype: int64

In [115]:
sweden_filter = gapminder_df['country'] == 'Sweden'

sweden_df = gapminder_df[sweden_filter].reset_index(drop=True)

sweden_df

   country continent  year  lifeExp      pop     gdpPercap iso_alpha  iso_num
0   Sweden    Europe  1952   71.860  7124673   8527.844662       SWE      752
1   Sweden    Europe  1957   72.490  7363802   9911.878226       SWE      752
2   Sweden    Europe  1962   73.370  7561588  12329.441920       SWE      752
3   Sweden    Europe  1967   74.160  7867931  15258.296970       SWE      752
4   Sweden    Europe  1972   74.720  8122293  17832.024640       SWE      752
5   Sweden    Europe  1977   75.440  8251648  18855.725210       SWE      752
6   Sweden    Europe  1982   76.420  8325260  20667.381250       SWE      752
7   Sweden    Europe  1987   77.190  8421403  23586.929270       SWE      752
8   Sweden    Europe  1992   78.160  8718867  23880.016830       SWE      752
9   Sweden    Europe  1997   79.390  8897619  25266.594990       SWE      752
10  Sweden    Europe  2002   80.040  8954175  29341.630930       SWE      752
11  Sweden    Europe  2007   80.884  9031088  33859.748350       SWE      752

In [116]:
nordic_countries = ['Sweden', 'Norway', 'Denmark', 'Iceland', 'Finland']

nordic_filter = gapminder_df['country'].isin(nordic_countries)

nordic_df = gapminder_df[nordic_filter].reset_index(drop=True)

nordic_df

    country continent  year  lifeExp      pop     gdpPercap iso_alpha  iso_num
0   Denmark    Europe  1952   70.780  4334000   9692.385245       DNK      208
1   Denmark    Europe  1957   71.810  4487831  11099.659350       DNK      208
2   Denmark    Europe  1962   72.350  4646899  13583.313510       DNK      208
3   Denmark    Europe  1967   72.960  4838800  15937.211230       DNK      208
4   Denmark    Europe  1972   73.470  4991596  18866.207210       DNK      208
5   Denmark    Europe  1977   74.690  5088419  20422.901500       DNK      208
6   Denmark    Europe  1982   74.630  5117810  21688.040480       DNK      208
7   Denmark    Europe  1987   74.800  5127024  25116.175810       DNK      208
8   Denmark    Europe  1992   75.330  5171393  26406.739850       DNK      208
9   Denmark    Europe  1997   76.110  5283663  29804.345670       DNK      208
10  Denmark    Europe  2002   77.180  5374693  32166.500060       DNK      208
11  Denmark    Europe  2007   78.332  5468120  35278.418740       DNK      208
12  Finland    Europe  1952   66.550  4090500   6424.519071       FIN      246
13  Finland    Europe  1957   67.490  4324000   7545.415386       FIN      246
14  Finland    Europe  1962   68.750  4491443   9371.842561       FIN      246
15  Finland    Europe  1967   69.830  4605744  10921.636260       FIN      246
16  Finland    Europe  1972   70.870  4639657  14358.875900       FIN      246
17  Finland    Europe  1977   72.520  4738902  15605.422830       FIN      246
18  Finland    Europe  1982   74.550  4826933  18533.157610       FIN      246
19  Finland    Europe  1987   74.830  4931729  21141.012230       FIN      246
20  Finland    Europe  1992   75.700  5041039  20647.164990       FIN      246
21  Finland    Europe  1997   77.130  5134406  23723.950200       FIN      246
22  Finland    Europe  2002   78.370  5193039  28204.590570       FIN      246
23  Finland    Europe  2007   79.313  5238460  33207.084400       FIN      246
24  Iceland    Europe  1952   72.490   147962   7267.688428       ISL      352
25  Iceland    Europe  1957   73.470   165110   9244.001412       ISL      352
26  Iceland    Europe  1962   73.680   182053  10350.159060       ISL      352
27  Iceland    Europe  1967   73.730   198676  13319.895680       ISL      352
28  Iceland    Europe  1972   74.460   209275  15798.063620       ISL      352
29  Iceland    Europe  1977   76.110   221823  19654.962470       ISL      352
30  Iceland    Europe  1982   76.990   233997  23269.607500       ISL      352
31  Iceland    Europe  1987   77.230   244676  26923.206280       ISL      352
32  Iceland    Europe  1992   78.770   259012  25144.392010       ISL      352
33  Iceland    Europe  1997   78.950   271192  28061.099660       ISL      352
34  Iceland    Europe  2002   80.500   288030  31163.201960       ISL      352
35  Iceland    Europe  2007   81.757   301931  36180.789190       ISL      352
36   Norway    Europe  1952   72.670  3327728  10095.421720       NOR      578
37   Norway    Europe  1957   73.440  3491938  11653.973040       NOR      578
38   Norway    Europe  1962   73.470  3638919  13450.401510       NOR      578
39   Norway    Europe  1967   74.080  3786019  16361.876470       NOR      578
40   Norway    Europe  1972   74.340  3933004  18965.055510       NOR      578
41   Norway    Europe  1977   75.370  4043205  23311.349390       NOR      578
42   Norway    Europe  1982   75.970  4114787  26298.635310       NOR      578
43   Norway    Europe  1987   75.890  4186147  31540.974800       NOR      578
44   Norway    Europe  1992   77.320  4286357  33965.661150       NOR      578
45   Norway    Europe  1997   78.320  4405672  41283.164330       NOR      578
46   Norway    Europe  2002   79.050  4535591  44683.975250       NOR      578
47   Norway    Europe  2007   80.196  4627926  49357.190170       NOR      578
48   Sweden    Europe  1952   71.860  7124673   8527.844662       SWE      752
49   Sweden    Europe  1957   72.490  7363802   9911.878226       SWE      752
50   Sweden    Europe  1962   73.370  7561588  12329.441920       SWE      752
51   Sweden    Europe  1967   74.160  7867931  15258.296970       SWE      752
52   Sweden    Europe  1972   74.720  8122293  17832.024640       SWE      752
53   Sweden    Europe  1977   75.440  8251648  18855.725210       SWE      752
54   Sweden    Europe  1982   76.420  8325260  20667.381250       SWE      752
55   Sweden    Europe  1987   77.190  8421403  23586.929270       SWE      752
56   Sweden    Europe  1992   78.160  8718867  23880.016830       SWE      752
57   Sweden    Europe  1997   79.390  8897619  25266.594990       SWE      752
58   Sweden    Europe  2002   80.040  8954175  29341.630930       SWE      752
59   Sweden    Europe  2007   80.884  9031088  33859.748350       SWE      752

____

# 3. Core Plotly Express Plot Types

**Scatter Plots**

Scatter plots are used to visualize the relationship between two continuous variables.

In [117]:
fig = px.scatter(gapminder_df, x='gdpPercap', y='lifeExp', title='Life Expectancy vs GDP per Capita')
fig.show()

In [118]:
fig = px.scatter(sweden_df, x='gdpPercap', y='lifeExp', title='Life Expectancy vs GDP per Capita')
fig.show()

### Adding color and size for categorical and continuous variables

We can enhance the scatter plot by adding color to differentiate continents and adjust marker size based on population.

**Note** that this adds several new dimensions to our visualisations!

In [119]:
gapminder_df.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4

In [120]:
fig = px.scatter(gapminder_df, x='gdpPercap', y='lifeExp', title='Life Expectancy vs GDP per Capita', color='continent')
fig.show()

In [121]:
fig = px.scatter(gapminder_df, x='gdpPercap', y='lifeExp', title='Life Expectancy vs GDP per Capita (logarithmic scale)', 
                 color='continent', log_x=True)
fig.show()

In [122]:
fig = px.scatter(gapminder_df, x='gdpPercap', y='lifeExp', title='Life Expectancy vs GDP per Capita as a Bubble Plot (logarithmic scale)', 
                 color='continent', size='pop', log_x=True)
fig.show()

**Line Plots**

Line plots are ideal for visualizing trends over time. Let's visualize life expectancy over the years for a single country.

In [123]:
fig = px.line(sweden_df, x='year', y='lifeExp', title='Life Expectancy Over Time for Sweden')
fig.show()

In [124]:
fig = px.line(nordic_df, x='year', y='lifeExp', title='Life Expectancy Over Time in Nordic Countries (1952-2007)', 
              color='country', hover_name='pop')
fig.show()

**Bar Charts**

Bar charts help compare data across categories. Here, we'll look at the average life expectancy by continent.

In [125]:
nordic_year_1952_filter = nordic_df['year'] == 1952

fig = px.bar(nordic_df[nordic_year_1952_filter], x='country', y='lifeExp', title='Life Expectancy in Nordic Countries 1952', 
             color='country', labels={'lifeExp':'Life Expectancy'})
fig.show()

**Stacked Bar Chart**

You can also create a grouped or stacked bar chart to see the trend of life expectancy by continent over time.

In [126]:
fig = px.bar(nordic_df, x='year', y='lifeExp', color='country', barmode='stack', title='LifeExp over time for Nordics (1952-2007)')
fig.show()

In [127]:
fig = px.bar(nordic_df, x='year', y='lifeExp', color='country', barmode='group', title='LifeExp over time for Nordics (1952-2007)')
fig.show()

**Bubble Charts**

Bubble charts are an extension of scatter plots where the size of the marker represents a third variable, such as population.

In [128]:
fig = px.scatter(gapminder_df, x='gdpPercap', y='lifeExp', title='Life Exptectancy vs GDP per capita as a Bubble Chart', 
                 log_x=True, color='continent', size='pop', size_max=60, hover_name='country')
fig.show()

**Faceted Plots**

Faceted plots allow you to break down the data into smaller plots based on categories like continent. This helps in comparing trends across subgroups.

In [129]:
fig = px.scatter(gapminder_df, x='gdpPercap', y='lifeExp', title='Life Exptectancy vs GDP per capita as a Bubble Chart', 
                 log_x=True, color='continent', size='pop', size_max=60, hover_name='country', facet_col='continent')
fig.show()

In [130]:
fig = px.scatter(nordic_df, x='gdpPercap', y='lifeExp', color='year', size='pop', facet_col='country')
fig.show()

___

## 4. Customizing Plotly Express Plots

Plotly Express allows for easy customization of titles, axis labels, colors, and more. Let’s look at some customization options.

In [131]:
fig = px.scatter(nordic_df, x='gdpPercap', y='lifeExp', color='year', size='pop', facet_col='country', 
                 title='Life Expectancy vs GDP per Capita for Nordic Countries (1952-2007)', 
                 labels={'lifeExp':'Life Expectancy', 'gdpPercap': 'GDP per Capita'})
fig.show()

**Changing Color Scales**

You can modify the color scale to enhance visual representation.

In [132]:
fig = px.scatter(nordic_df, x='gdpPercap', y='lifeExp', color='year', size='pop', facet_col='country', 
                 title='Life Expectancy vs GDP per Capita for Nordic Countries (1952-2007)', 
                 labels={'lifeExp':'Life Expectancy', 'gdpPercap': 'GDP per Capita'}, color_continuous_scale='Viridis')
fig.show()

**Adjusting marker size and opacity**

You can control marker size and transparency to make dense plots easier to read.

In [133]:
fig = px.scatter(gapminder_df, x='gdpPercap', y='lifeExp', color='year', size='pop', 
                 title='Life Expectancy vs GDP per Capita for Nordic Countries (1952-2007)', 
                 labels={'lifeExp':'Life Expectancy', 'gdpPercap': 'GDP per Capita'}, color_continuous_scale='Viridis',
                 log_x=True, size_max=50, opacity=0.4)
fig.show()

____

## 5. Interactivity in Plotly Express

One of the major advantages of Plotly Express is the built-in interactivity.

**Combining Facets and Animations**

You can combine faceting with animations to create multi-dimensional visualizations.

In [134]:
nordic_gdp_per_cap_max = nordic_df['gdpPercap'].max()
nordic_life_exp_max = nordic_df['lifeExp'].max()

fig = px.scatter(nordic_df, x='gdpPercap', y='lifeExp', color='country', size='pop', animation_frame='year',
                 range_x = [0, nordic_gdp_per_cap_max+2000], range_y = [60, nordic_life_exp_max+5])
fig.show()

# Hover settings

In [135]:
fig = px.line(nordic_df, x='year', y='gdpPercap', color='country')

fig.update_layout(hovermode='x')
fig.update_xaxes(showspikes=True, spikedash='solid', spikemode='across', spikesnap='cursor')

fig.show()

# Pie chart

In [136]:
year_2007_filter = gapminder_df['year'] == 2007

nordic_2007_df = gapminder_df[nordic_filter & year_2007_filter].reset_index(drop=True)

nordic_2007_df

   country continent  year  lifeExp      pop    gdpPercap iso_alpha  iso_num
0  Denmark    Europe  2007   78.332  5468120  35278.41874       DNK      208
1  Finland    Europe  2007   79.313  5238460  33207.08440       FIN      246
2  Iceland    Europe  2007   81.757   301931  36180.78919       ISL      352
3   Norway    Europe  2007   80.196  4627926  49357.19017       NOR      578
4   Sweden    Europe  2007   80.884  9031088  33859.74835       SWE      752

In [137]:
fig = px.pie(nordic_2007_df, values='pop', names='country', hover_data='gdpPercap')
fig.show()